// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "../ui.h"

void ui_scrnAnalog_screen_init(void)
{
    ui_scrnAnalog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnHome3 = lv_imgbtn_create(ui_scrnAnalog);
    lv_imgbtn_set_src(ui_btnHome3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_40px_png, NULL);
    lv_obj_set_height(ui_btnHome3, 44);
    lv_obj_set_width(ui_btnHome3, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_x(ui_btnHome3, 10);
    lv_obj_set_y(ui_btnHome3, -10);
    lv_obj_set_align(ui_btnHome3, LV_ALIGN_BOTTOM_LEFT);

    ui_sliderDACVout = lv_slider_create(ui_scrnAnalog);
    lv_slider_set_range(ui_sliderDACVout, 0, 255);
    lv_slider_set_value(ui_sliderDACVout, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderDACVout) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sliderDACVout, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderDACVout, 250);
    lv_obj_set_height(ui_sliderDACVout, 20);
    lv_obj_set_x(ui_sliderDACVout, 0);
    lv_obj_set_y(ui_sliderDACVout, -100);
    lv_obj_set_align(ui_sliderDACVout, LV_ALIGN_CENTER);


    ui_Label14 = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -200);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "DAC Voltage Out");

    ui_valVout = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_valVout, 80);
    lv_obj_set_height(ui_valVout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valVout, -24);
    lv_obj_set_y(ui_valVout, -150);
    lv_obj_set_align(ui_valVout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valVout, "0.0");
    lv_obj_set_style_text_align(ui_valVout, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valVout, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valVout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valVout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_valVout, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_valVout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_valVout, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_valVout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_valVout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelV = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_labelV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelV, 30);
    lv_obj_set_y(ui_labelV, -150);
    lv_obj_set_align(ui_labelV, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelV, "V");
    lv_obj_set_style_text_font(ui_labelV, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -85);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Vin");

    ui_lblV1 = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_lblV1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblV1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblV1, -45);
    lv_obj_set_y(ui_lblV1, 40);
    lv_obj_set_align(ui_lblV1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblV1, "V");
    lv_obj_set_style_text_font(ui_lblV1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valVin = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_valVin, 80);
    lv_obj_set_height(ui_valVin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valVin, -100);
    lv_obj_set_y(ui_valVin, 40);
    lv_obj_set_align(ui_valVin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valVin, "0.0");
    lv_obj_set_style_text_align(ui_valVin, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valVin, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valVin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valVin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_valVin, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_valVin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_valVin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_valVin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_valVin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_val0to10V = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_val0to10V, 80);
    lv_obj_set_height(ui_val0to10V, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_val0to10V, 65);
    lv_obj_set_y(ui_val0to10V, 40);
    lv_obj_set_align(ui_val0to10V, LV_ALIGN_CENTER);
    lv_label_set_text(ui_val0to10V, "0.0");
    lv_obj_set_style_text_align(ui_val0to10V, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_val0to10V, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_val0to10V, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_val0to10V, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_val0to10V, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_val0to10V, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_val0to10V, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_val0to10V, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_val0to10V, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 80);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "0 to 10V");

    ui_lblV2 = lv_label_create(ui_scrnAnalog);
    lv_obj_set_width(ui_lblV2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblV2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblV2, 120);
    lv_obj_set_y(ui_lblV2, 40);
    lv_obj_set_align(ui_lblV2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblV2, "V");
    lv_obj_set_style_text_font(ui_lblV2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome3, ui_event_btnHome3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sliderDACVout, ui_event_sliderDACVout, LV_EVENT_ALL, NULL);

}
