// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "../ui.h"

void ui_scrnCAN_screen_init(void)
{
    ui_scrnCAN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_scrnCAN);
    lv_obj_set_width(ui_Panel2, 300);
    lv_obj_set_height(ui_Panel2, 208);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 10);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnRxCAN = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_btnRxCAN, 146);
    lv_obj_set_height(ui_btnRxCAN, 35);
    lv_obj_set_align(ui_btnRxCAN, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnRxCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRxCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RxBtnTxt = lv_label_create(ui_btnRxCAN);
    lv_obj_set_width(ui_RxBtnTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RxBtnTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RxBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RxBtnTxt, "Start");

    ui_scrnCAN_Label6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_scrnCAN_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrnCAN_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrnCAN_Label6, 0);
    lv_obj_set_y(ui_scrnCAN_Label6, -10);
    lv_obj_set_align(ui_scrnCAN_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_scrnCAN_Label6, "CAN Rx:");
    lv_obj_set_style_text_font(ui_scrnCAN_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrnCAN_Label2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_scrnCAN_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrnCAN_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrnCAN_Label2, -90);
    lv_obj_set_y(ui_scrnCAN_Label2, -40);
    lv_obj_set_align(ui_scrnCAN_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrnCAN_Label2, "Rx ID FILTER:");

    ui_txtFilterID = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_txtFilterID, 114);
    lv_obj_set_height(ui_txtFilterID, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_txtFilterID, 20);
    lv_obj_set_y(ui_txtFilterID, -40);
    lv_obj_set_align(ui_txtFilterID, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_txtFilterID, 8);
    lv_textarea_set_one_line(ui_txtFilterID, true);
    lv_obj_clear_flag(ui_txtFilterID, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_txtFilterID, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_border_color(ui_txtFilterID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtFilterID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Panel1 = lv_obj_create(ui_scrnCAN);
    lv_obj_set_width(ui_Panel1, 290);
    lv_obj_set_height(ui_Panel1, 35);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -110);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCANRxMsg = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblCANRxMsg, 280);
    lv_obj_set_height(ui_lblCANRxMsg, 15);
    lv_obj_set_x(ui_lblCANRxMsg, 0);
    lv_obj_set_y(ui_lblCANRxMsg, -5);
    lv_obj_set_align(ui_lblCANRxMsg, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCANRxMsg, "");
    lv_obj_set_style_text_font(ui_lblCANRxMsg, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_scrnCAN);
    lv_obj_set_width(ui_Panel3, 300);
    lv_obj_set_height(ui_Panel3, 138);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 70);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrnCAN_Label4 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_scrnCAN_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrnCAN_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrnCAN_Label4, 0);
    lv_obj_set_y(ui_scrnCAN_Label4, -10);
    lv_obj_set_align(ui_scrnCAN_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_scrnCAN_Label4, "CAN Tx:");
    lv_obj_set_style_text_font(ui_scrnCAN_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtCANTxID = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_txtCANTxID, 100);
    lv_obj_set_height(ui_txtCANTxID, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_txtCANTxID, -90);
    lv_obj_set_y(ui_txtCANTxID, -10);
    lv_obj_set_align(ui_txtCANTxID, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_txtCANTxID, 8);
    lv_textarea_set_text(ui_txtCANTxID, "0100");
    lv_textarea_set_one_line(ui_txtCANTxID, true);
    lv_obj_clear_flag(ui_txtCANTxID, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_txtCANTxID, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_txtCANTxID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_txtCANTxID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtCANTxID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_txtCANTxData = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_txtCANTxData, 170);
    lv_obj_set_height(ui_txtCANTxData, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_txtCANTxData, 55);
    lv_obj_set_y(ui_txtCANTxData, -10);
    lv_obj_set_align(ui_txtCANTxData, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_txtCANTxData, 16);
    lv_textarea_set_text(ui_txtCANTxData, "01030507090A0C0E");
    lv_textarea_set_one_line(ui_txtCANTxData, true);
    lv_obj_clear_flag(ui_txtCANTxData, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_txtCANTxData, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_txtCANTxData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_txtCANTxData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_txtCANTxData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_btnSendCANMsg = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_btnSendCANMsg, 146);
    lv_obj_set_height(ui_btnSendCANMsg, 35);
    lv_obj_set_x(ui_btnSendCANMsg, 0);
    lv_obj_set_y(ui_btnSendCANMsg, 40);
    lv_obj_set_align(ui_btnSendCANMsg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSendCANMsg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSendCANMsg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrnCAN_Label5 = lv_label_create(ui_btnSendCANMsg);
    lv_obj_set_width(ui_scrnCAN_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrnCAN_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_scrnCAN_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrnCAN_Label5, "Send");

    ui_Label2 = lv_label_create(ui_scrnCAN);
    lv_obj_set_width(ui_Label2, 200);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 45);
    lv_obj_set_y(ui_Label2, 200);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "All hex values less than 0x10 must be entered as two digits (ie enter F as 0F)");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xED1C2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnHome1 = lv_imgbtn_create(ui_scrnCAN);
    lv_imgbtn_set_src(ui_btnHome1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_40px_png, NULL);
    lv_obj_set_height(ui_btnHome1, 44);
    lv_obj_set_width(ui_btnHome1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_x(ui_btnHome1, 10);
    lv_obj_set_y(ui_btnHome1, -10);
    lv_obj_set_align(ui_btnHome1, LV_ALIGN_BOTTOM_LEFT);

    lv_obj_add_event_cb(ui_btnRxCAN, ui_event_btnRxCAN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSendCANMsg, ui_event_btnSendCANMsg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnHome1, ui_event_btnHome1, LV_EVENT_ALL, NULL);

}
