// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrnHome
void ui_scrnHome_screen_init(void);
lv_obj_t * ui_scrnHome;
void ui_event_btnCAN(lv_event_t * e);
lv_obj_t * ui_btnCAN;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image2;
void ui_event_btnGPIO(lv_event_t * e);
lv_obj_t * ui_btnGPIO;
lv_obj_t * ui_Label3;
void ui_event_btnAnalog(lv_event_t * e);
lv_obj_t * ui_btnAnalog;
lv_obj_t * ui_Label4;
void ui_event_btnPulse(lv_event_t * e);
lv_obj_t * ui_btnPulse;
lv_obj_t * ui_Label5;


// SCREEN: ui_scrnCAN
void ui_scrnCAN_screen_init(void);
lv_obj_t * ui_scrnCAN;
lv_obj_t * ui_Panel2;
void ui_event_btnRxCAN(lv_event_t * e);
lv_obj_t * ui_btnRxCAN;
lv_obj_t * ui_RxBtnTxt;
lv_obj_t * ui_scrnCAN_Label6;
lv_obj_t * ui_scrnCAN_Label2;
lv_obj_t * ui_txtFilterID;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_lblCANRxMsg;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_scrnCAN_Label4;
lv_obj_t * ui_txtCANTxID;
lv_obj_t * ui_txtCANTxData;
void ui_event_btnSendCANMsg(lv_event_t * e);
lv_obj_t * ui_btnSendCANMsg;
lv_obj_t * ui_scrnCAN_Label5;
lv_obj_t * ui_Label2;
void ui_event_btnHome1(lv_event_t * e);
lv_obj_t * ui_btnHome1;


// SCREEN: ui_scrnGPIO
void ui_scrnGPIO_screen_init(void);
lv_obj_t * ui_scrnGPIO;
void ui_event_btnHome2(lv_event_t * e);
lv_obj_t * ui_btnHome2;
void ui_event_swtGPO3(lv_event_t * e);
lv_obj_t * ui_swtGPO3;
void ui_event_swtGPO4(lv_event_t * e);
lv_obj_t * ui_swtGPO4;
void ui_event_swtGPO5(lv_event_t * e);
lv_obj_t * ui_swtGPO5;
lv_obj_t * ui_lblGPI1Ind;
lv_obj_t * ui_lblGPI2Ind;
void ui_event_swtBeep(lv_event_t * e);
lv_obj_t * ui_swtBeep;
void ui_event_swtCANTerm(lv_event_t * e);
lv_obj_t * ui_swtCANTerm;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;


// SCREEN: ui_scrnAnalog
void ui_scrnAnalog_screen_init(void);
lv_obj_t * ui_scrnAnalog;
void ui_event_btnHome3(lv_event_t * e);
lv_obj_t * ui_btnHome3;
void ui_event_sliderDACVout(lv_event_t * e);
lv_obj_t * ui_sliderDACVout;
lv_obj_t * ui_Label14;
lv_obj_t * ui_valVout;
lv_obj_t * ui_labelV;
lv_obj_t * ui_Label15;
lv_obj_t * ui_lblV1;
lv_obj_t * ui_valVin;
lv_obj_t * ui_val0to10V;
lv_obj_t * ui_Label16;
lv_obj_t * ui_lblV2;


// SCREEN: ui_scrnPulse
void ui_scrnPulse_screen_init(void);
lv_obj_t * ui_scrnPulse;
void ui_event_btnHome4(lv_event_t * e);
lv_obj_t * ui_btnHome4;
lv_obj_t * ui_Label17;
void ui_event_btnFreqUp(lv_event_t * e);
lv_obj_t * ui_btnFreqUp;
lv_obj_t * ui_Label18;
void ui_event_btnFreqDown(lv_event_t * e);
lv_obj_t * ui_btnFreqDown;
lv_obj_t * ui_Label19;
void ui_event_btnDCUp(lv_event_t * e);
lv_obj_t * ui_btnDCUp;
lv_obj_t * ui_Label20;
void ui_event_btnDCDown(lv_event_t * e);
lv_obj_t * ui_btnDCDown;
lv_obj_t * ui_Label21;
lv_obj_t * ui_valPWMOutFreq;
lv_obj_t * ui_valPWMOutDC;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_valPulseIn;
lv_obj_t * ui_Label28;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnCAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScreen(e);
    }
}
void ui_event_btnGPIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScreen(e);
    }
}
void ui_event_btnAnalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScreen(e);
    }
}
void ui_event_btnPulse(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScreen(e);
    }
}
void ui_event_btnRxCAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnRxCANMsg(e);
    }
}
void ui_event_btnSendCANMsg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnTxCANMsg(e);
    }
}
void ui_event_btnHome1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScrnHome(e);
    }
}
void ui_event_btnHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScrnHome(e);
    }
}
void ui_event_swtGPO3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        swtGPO3Toggle(e);
    }
}
void ui_event_swtGPO4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        swtGPO4Toggle(e);
    }
}
void ui_event_swtGPO5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        swtGPO5Toggle(e);
    }
}
void ui_event_swtBeep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        swtBeepToggle(e);
    }
}
void ui_event_swtCANTerm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        swtCANTermToggle(e);
    }
}
void ui_event_btnHome3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScrnHome(e);
    }
}
void ui_event_sliderDACVout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        UpdtDACVal(e);
    }
}
void ui_event_btnHome4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chngScrnHome(e);
    }
}
void ui_event_btnFreqUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnFreqUp_clk(e);
    }
}
void ui_event_btnFreqDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnFreqDwn_clk(e);
    }
}
void ui_event_btnDCUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnDCUp_clk(e);
    }
}
void ui_event_btnDCDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnDCDwn_clk(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrnHome_screen_init();
    ui_scrnCAN_screen_init();
    ui_scrnGPIO_screen_init();
    ui_scrnAnalog_screen_init();
    ui_scrnPulse_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrnHome);
}
