// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#ifndef _TAPCAN_DEMO_UI_H
#define _TAPCAN_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrnHome
void ui_scrnHome_screen_init(void);
extern lv_obj_t * ui_scrnHome;
void ui_event_btnCAN(lv_event_t * e);
extern lv_obj_t * ui_btnCAN;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
void ui_event_btnGPIO(lv_event_t * e);
extern lv_obj_t * ui_btnGPIO;
extern lv_obj_t * ui_Label3;
void ui_event_btnAnalog(lv_event_t * e);
extern lv_obj_t * ui_btnAnalog;
extern lv_obj_t * ui_Label4;
void ui_event_btnPulse(lv_event_t * e);
extern lv_obj_t * ui_btnPulse;
extern lv_obj_t * ui_Label5;
// SCREEN: ui_scrnCAN
void ui_scrnCAN_screen_init(void);
extern lv_obj_t * ui_scrnCAN;
extern lv_obj_t * ui_Panel2;
void ui_event_btnRxCAN(lv_event_t * e);
extern lv_obj_t * ui_btnRxCAN;
extern lv_obj_t * ui_RxBtnTxt;
extern lv_obj_t * ui_scrnCAN_Label6;
extern lv_obj_t * ui_scrnCAN_Label2;
extern lv_obj_t * ui_txtFilterID;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblCANRxMsg;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_scrnCAN_Label4;
extern lv_obj_t * ui_txtCANTxID;
extern lv_obj_t * ui_txtCANTxData;
void ui_event_btnSendCANMsg(lv_event_t * e);
extern lv_obj_t * ui_btnSendCANMsg;
extern lv_obj_t * ui_scrnCAN_Label5;
extern lv_obj_t * ui_Label2;
void ui_event_btnHome1(lv_event_t * e);
extern lv_obj_t * ui_btnHome1;
// SCREEN: ui_scrnGPIO
void ui_scrnGPIO_screen_init(void);
extern lv_obj_t * ui_scrnGPIO;
void ui_event_btnHome2(lv_event_t * e);
extern lv_obj_t * ui_btnHome2;
void ui_event_swtGPO3(lv_event_t * e);
extern lv_obj_t * ui_swtGPO3;
void ui_event_swtGPO4(lv_event_t * e);
extern lv_obj_t * ui_swtGPO4;
void ui_event_swtGPO5(lv_event_t * e);
extern lv_obj_t * ui_swtGPO5;
extern lv_obj_t * ui_lblGPI1Ind;
extern lv_obj_t * ui_lblGPI2Ind;
void ui_event_swtBeep(lv_event_t * e);
extern lv_obj_t * ui_swtBeep;
void ui_event_swtCANTerm(lv_event_t * e);
extern lv_obj_t * ui_swtCANTerm;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_scrnAnalog
void ui_scrnAnalog_screen_init(void);
extern lv_obj_t * ui_scrnAnalog;
void ui_event_btnHome3(lv_event_t * e);
extern lv_obj_t * ui_btnHome3;
void ui_event_sliderDACVout(lv_event_t * e);
extern lv_obj_t * ui_sliderDACVout;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_valVout;
extern lv_obj_t * ui_labelV;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_lblV1;
extern lv_obj_t * ui_valVin;
extern lv_obj_t * ui_val0to10V;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_lblV2;
// SCREEN: ui_scrnPulse
void ui_scrnPulse_screen_init(void);
extern lv_obj_t * ui_scrnPulse;
void ui_event_btnHome4(lv_event_t * e);
extern lv_obj_t * ui_btnHome4;
extern lv_obj_t * ui_Label17;
void ui_event_btnFreqUp(lv_event_t * e);
extern lv_obj_t * ui_btnFreqUp;
extern lv_obj_t * ui_Label18;
void ui_event_btnFreqDown(lv_event_t * e);
extern lv_obj_t * ui_btnFreqDown;
extern lv_obj_t * ui_Label19;
void ui_event_btnDCUp(lv_event_t * e);
extern lv_obj_t * ui_btnDCUp;
extern lv_obj_t * ui_Label20;
void ui_event_btnDCDown(lv_event_t * e);
extern lv_obj_t * ui_btnDCDown;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_valPWMOutFreq;
extern lv_obj_t * ui_valPWMOutDC;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_valPulseIn;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_tapcan_280px_png);    // assets/TapCAN_280px.png
LV_IMG_DECLARE(ui_img_home_40px_png);    // assets/Home_40px.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
