// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void chngScreen(lv_event_t * e);
void btnRxCANMsg(lv_event_t * e);
void btnTxCANMsg(lv_event_t * e);
void chngScrnHome(lv_event_t * e);
void swtGPO3Toggle(lv_event_t * e);
void swtGPO4Toggle(lv_event_t * e);
void swtGPO5Toggle(lv_event_t * e);
void swtBeepToggle(lv_event_t * e);
void swtCANTermToggle(lv_event_t * e);
void UpdtDACVal(lv_event_t * e);
void btnFreqUp_clk(lv_event_t * e);
void btnFreqDwn_clk(lv_event_t * e);
void btnDCUp_clk(lv_event_t * e);
void btnDCDwn_clk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
