// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "ui.h"
#include "gpio_ext.h"
#include "anlg_out.h"
#include "pulse.h"
#include "CAN.h"

void swtBeepToggle(lv_event_t * e)
{
	set_gpo_beep(lv_obj_has_state(ui_swtBeep,LV_STATE_CHECKED));
}

void swtGPO3Toggle(lv_event_t * e)
{
	set_gpo_3(lv_obj_has_state(ui_swtGPO3,LV_STATE_CHECKED));
}

void swtGPO4Toggle(lv_event_t * e)
{
	set_gpo_4(lv_obj_has_state(ui_swtGPO4,LV_STATE_CHECKED));
}

void swtGPO5Toggle(lv_event_t * e)
{
	set_gpo_5(lv_obj_has_state(ui_swtGPO5,LV_STATE_CHECKED));
}

void swtCANTermToggle(lv_event_t * e)
{
	set_gpo_CANTerm(lv_obj_has_state(ui_swtBeep,LV_STATE_CHECKED));
}

void chngScreen(lv_event_t * e)
{
	lv_obj_t *target = lv_event_get_target(e);
	
	if (target == ui_btnCAN)
	{
		lv_scr_load(ui_scrnCAN);
	}
	else if (target == ui_btnGPIO)
	{
		lv_scr_load(ui_scrnGPIO);
	}
	else if (target == ui_btnAnalog)
	{
		lv_scr_load(ui_scrnAnalog);
	}
	else if (target == ui_btnPulse)
	{
		lv_scr_load(ui_scrnPulse);
	}	
}

void chngScrnHome(lv_event_t * e)
{
	lv_scr_load(ui_scrnHome);
}

void UpdtDACVal(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);
    uint8_t slider_val = (uint8_t)lv_slider_get_value(slider);    
	float fVOut = slider_val/25.5;
	lv_label_set_text_fmt(ui_valVout,"%.1f",fVOut);    
	set_DAC_val(slider_val);
}

void btnDCUp_clk(lv_event_t * e)
{
	SetPWMOutDC(1);
}

void btnDCDwn_clk(lv_event_t * e)
{
	SetPWMOutDC(0);
}

void btnFreqUp_clk(lv_event_t * e)
{
	SetPWMOutFreq(1);
}

void btnFreqDwn_clk(lv_event_t * e)
{
	SetPWMOutFreq(0);
}

void btnTxCANMsg(lv_event_t * e)
{
	fnCAN_Tx();
}

void btnRxCANMsg(lv_event_t * e)
{
	if(bCAN_RxActv)
	{
		lv_label_set_text(ui_RxBtnTxt, "Start");
		bCAN_RxActv=false;
	}
	else
	{
		lv_label_set_text(ui_RxBtnTxt, "Stop");
		bCAN_RxActv=true;
	}
	fnCAN_cntrl_Rx();
}