// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "../ui.h"

void ui_scrnPulse_screen_init(void)
{
    ui_scrnPulse = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnPulse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnHome4 = lv_imgbtn_create(ui_scrnPulse);
    lv_imgbtn_set_src(ui_btnHome4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_40px_png, NULL);
    lv_obj_set_height(ui_btnHome4, 44);
    lv_obj_set_width(ui_btnHome4, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_x(ui_btnHome4, 10);
    lv_obj_set_y(ui_btnHome4, -10);
    lv_obj_set_align(ui_btnHome4, LV_ALIGN_BOTTOM_LEFT);

    ui_Label17 = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -9);
    lv_obj_set_y(ui_Label17, -196);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "PWM Out");

    ui_btnFreqUp = lv_btn_create(ui_scrnPulse);
    lv_obj_set_width(ui_btnFreqUp, 50);
    lv_obj_set_height(ui_btnFreqUp, 50);
    lv_obj_set_x(ui_btnFreqUp, -114);
    lv_obj_set_y(ui_btnFreqUp, -112);
    lv_obj_set_align(ui_btnFreqUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFreqUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFreqUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_btnFreqUp);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "UP");

    ui_btnFreqDown = lv_btn_create(ui_scrnPulse);
    lv_obj_set_width(ui_btnFreqDown, 50);
    lv_obj_set_height(ui_btnFreqDown, 50);
    lv_obj_set_x(ui_btnFreqDown, -114);
    lv_obj_set_y(ui_btnFreqDown, -47);
    lv_obj_set_align(ui_btnFreqDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFreqDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFreqDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_btnFreqDown);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "DWN");

    ui_btnDCUp = lv_btn_create(ui_scrnPulse);
    lv_obj_set_width(ui_btnDCUp, 50);
    lv_obj_set_height(ui_btnDCUp, 50);
    lv_obj_set_x(ui_btnDCUp, 116);
    lv_obj_set_y(ui_btnDCUp, -110);
    lv_obj_set_align(ui_btnDCUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDCUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDCUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_btnDCUp);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "UP");

    ui_btnDCDown = lv_btn_create(ui_scrnPulse);
    lv_obj_set_width(ui_btnDCDown, 50);
    lv_obj_set_height(ui_btnDCDown, 50);
    lv_obj_set_x(ui_btnDCDown, 116);
    lv_obj_set_y(ui_btnDCDown, -47);
    lv_obj_set_align(ui_btnDCDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDCDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDCDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_btnDCDown);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "DWN");

    ui_valPWMOutFreq = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_valPWMOutFreq, 90);
    lv_obj_set_height(ui_valPWMOutFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valPWMOutFreq, -36);
    lv_obj_set_y(ui_valPWMOutFreq, -80);
    lv_obj_set_align(ui_valPWMOutFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valPWMOutFreq, "");
    lv_obj_set_style_text_align(ui_valPWMOutFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valPWMOutFreq, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valPWMOutFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valPWMOutFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_valPWMOutFreq, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valPWMOutDC = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_valPWMOutDC, 60);
    lv_obj_set_height(ui_valPWMOutDC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valPWMOutDC, 48);
    lv_obj_set_y(ui_valPWMOutDC, -81);
    lv_obj_set_align(ui_valPWMOutDC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valPWMOutDC, "");
    lv_obj_set_style_text_align(ui_valPWMOutDC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valPWMOutDC, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valPWMOutDC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valPWMOutDC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_valPWMOutDC, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -41);
    lv_obj_set_y(ui_Label24, -119);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Hz");

    ui_Label25 = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 37);
    lv_obj_set_y(ui_Label25, -118);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "% DC");

    ui_Label26 = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 0);
    lv_obj_set_y(ui_Label26, 36);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Pulse In");

    ui_valPulseIn = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_valPulseIn, 90);
    lv_obj_set_height(ui_valPulseIn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valPulseIn, -37);
    lv_obj_set_y(ui_valPulseIn, 80);
    lv_obj_set_align(ui_valPulseIn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valPulseIn, "");
    lv_obj_set_style_text_align(ui_valPulseIn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_valPulseIn, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valPulseIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valPulseIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_valPulseIn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_scrnPulse);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 31);
    lv_obj_set_y(ui_Label28, 80);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Hz");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome4, ui_event_btnHome4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFreqUp, ui_event_btnFreqUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFreqDown, ui_event_btnFreqDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDCUp, ui_event_btnDCUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDCDown, ui_event_btnDCDown, LV_EVENT_ALL, NULL);

}
