// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "../ui.h"

void ui_scrnGPIO_screen_init(void)
{
    ui_scrnGPIO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnGPIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnHome2 = lv_imgbtn_create(ui_scrnGPIO);
    lv_imgbtn_set_src(ui_btnHome2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_40px_png, NULL);
    lv_obj_set_height(ui_btnHome2, 44);
    lv_obj_set_width(ui_btnHome2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_x(ui_btnHome2, 10);
    lv_obj_set_y(ui_btnHome2, -10);
    lv_obj_set_align(ui_btnHome2, LV_ALIGN_BOTTOM_LEFT);

    ui_swtGPO3 = lv_switch_create(ui_scrnGPIO);
    lv_obj_set_width(ui_swtGPO3, 80);
    lv_obj_set_height(ui_swtGPO3, 40);
    lv_obj_set_x(ui_swtGPO3, -75);
    lv_obj_set_y(ui_swtGPO3, 20);
    lv_obj_set_align(ui_swtGPO3, LV_ALIGN_TOP_MID);


    ui_swtGPO4 = lv_switch_create(ui_scrnGPIO);
    lv_obj_set_width(ui_swtGPO4, 80);
    lv_obj_set_height(ui_swtGPO4, 40);
    lv_obj_set_x(ui_swtGPO4, -75);
    lv_obj_set_y(ui_swtGPO4, 80);
    lv_obj_set_align(ui_swtGPO4, LV_ALIGN_TOP_MID);


    ui_swtGPO5 = lv_switch_create(ui_scrnGPIO);
    lv_obj_set_width(ui_swtGPO5, 80);
    lv_obj_set_height(ui_swtGPO5, 40);
    lv_obj_set_x(ui_swtGPO5, -75);
    lv_obj_set_y(ui_swtGPO5, 140);
    lv_obj_set_align(ui_swtGPO5, LV_ALIGN_TOP_MID);


    ui_lblGPI1Ind = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_lblGPI1Ind, 40);
    lv_obj_set_height(ui_lblGPI1Ind, 40);
    lv_obj_set_x(ui_lblGPI1Ind, -75);
    lv_obj_set_y(ui_lblGPI1Ind, 320);
    lv_obj_set_align(ui_lblGPI1Ind, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblGPI1Ind, "");
    lv_obj_set_style_bg_color(ui_lblGPI1Ind, lv_color_hex(0x00A000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblGPI1Ind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblGPI1Ind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblGPI1Ind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblGPI1Ind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGPI2Ind = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_lblGPI2Ind, 40);
    lv_obj_set_height(ui_lblGPI2Ind, 40);
    lv_obj_set_x(ui_lblGPI2Ind, -75);
    lv_obj_set_y(ui_lblGPI2Ind, 380);
    lv_obj_set_align(ui_lblGPI2Ind, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblGPI2Ind, "");
    lv_obj_set_style_bg_color(ui_lblGPI2Ind, lv_color_hex(0x00A000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblGPI2Ind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblGPI2Ind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblGPI2Ind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblGPI2Ind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swtBeep = lv_switch_create(ui_scrnGPIO);
    lv_obj_set_width(ui_swtBeep, 80);
    lv_obj_set_height(ui_swtBeep, 40);
    lv_obj_set_x(ui_swtBeep, -75);
    lv_obj_set_y(ui_swtBeep, 200);
    lv_obj_set_align(ui_swtBeep, LV_ALIGN_TOP_MID);


    ui_swtCANTerm = lv_switch_create(ui_scrnGPIO);
    lv_obj_set_width(ui_swtCANTerm, 80);
    lv_obj_set_height(ui_swtCANTerm, 40);
    lv_obj_set_x(ui_swtCANTerm, -75);
    lv_obj_set_y(ui_swtCANTerm, 260);
    lv_obj_set_align(ui_swtCANTerm, LV_ALIGN_TOP_MID);


    ui_Label7 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 50);
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "GPO 3");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 50);
    lv_obj_set_y(ui_Label8, 80);
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "GPO 4");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 50);
    lv_obj_set_y(ui_Label9, 140);
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "GPO 5");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 50);
    lv_obj_set_y(ui_Label10, 200);
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "BEEP");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 60);
    lv_obj_set_y(ui_Label11, 260);
    lv_obj_set_align(ui_Label11, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Label11, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label11, "CAN TERM");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 50);
    lv_obj_set_y(ui_Label12, 320);
    lv_obj_set_align(ui_Label12, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label12, "GPI 1");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_scrnGPIO);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 50);
    lv_obj_set_y(ui_Label13, 380);
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label13, "GPI 2");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnHome2, ui_event_btnHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtGPO3, ui_event_swtGPO3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtGPO4, ui_event_swtGPO4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtGPO5, ui_event_swtGPO5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtBeep, ui_event_swtBeep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtCANTerm, ui_event_swtCANTerm, LV_EVENT_ALL, NULL);

}
