// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: TapCAN_demo

#include "../ui.h"

void ui_scrnHome_screen_init(void)
{
    ui_scrnHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnCAN = lv_btn_create(ui_scrnHome);
    lv_obj_set_width(ui_btnCAN, 200);
    lv_obj_set_height(ui_btnCAN, 50);
    lv_obj_set_x(ui_btnCAN, 0);
    lv_obj_set_y(ui_btnCAN, -100);
    lv_obj_set_align(ui_btnCAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCAN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_btnCAN);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CAN");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_scrnHome);
    lv_img_set_src(ui_Image2, &ui_img_tapcan_280px_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnGPIO = lv_btn_create(ui_scrnHome);
    lv_obj_set_width(ui_btnGPIO, 200);
    lv_obj_set_height(ui_btnGPIO, 50);
    lv_obj_set_x(ui_btnGPIO, 0);
    lv_obj_set_y(ui_btnGPIO, -20);
    lv_obj_set_align(ui_btnGPIO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGPIO, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnGPIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_btnGPIO);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "GPIO");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnAnalog = lv_btn_create(ui_scrnHome);
    lv_obj_set_width(ui_btnAnalog, 200);
    lv_obj_set_height(ui_btnAnalog, 50);
    lv_obj_set_x(ui_btnAnalog, 0);
    lv_obj_set_y(ui_btnAnalog, 55);
    lv_obj_set_align(ui_btnAnalog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAnalog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAnalog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_btnAnalog);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Analog");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPulse = lv_btn_create(ui_scrnHome);
    lv_obj_set_width(ui_btnPulse, 200);
    lv_obj_set_height(ui_btnPulse, 50);
    lv_obj_set_x(ui_btnPulse, 0);
    lv_obj_set_y(ui_btnPulse, 130);
    lv_obj_set_align(ui_btnPulse, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPulse, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPulse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_btnPulse, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_btnPulse);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Pulse");

    lv_obj_add_event_cb(ui_btnCAN, ui_event_btnCAN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGPIO, ui_event_btnGPIO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnAnalog, ui_event_btnAnalog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPulse, ui_event_btnPulse, LV_EVENT_ALL, NULL);

}
